// Language Configuration
const languages = {
    en: {
        name: 'English',
        code: 'en'
    },
    hi: {
        name: 'हिंदी',
        code: 'hi'
    }
};

// Translations
const translations = {
    en: {
        // Navigation
        home: 'Home',
        help: 'Help',
        allTopics: 'All Topics',
        aboutUs: 'About Us',
        
        // Accessibility
        contrastToggle: 'Toggle high contrast mode',
        fontSizeToggle: 'Toggle large text',
        voiceToggle: 'Toggle voice assistance',
        languageToggle: 'Toggle language',
        
        // Homepage
        welcomeTitle: 'MitraYug - Bridging Generations through Digital Literacy',
        welcomeText: 'Welcome to MitraYug, your friendly guide to learning digital skills. We make technology simple and accessible for everyone.',
        startLearning: 'Start Learning',
        
        // Topic Categories
        basicPhone: 'Basic Phone Operations',
        messaging: 'Messaging and Communication',
        apps: 'Apps and Device Management',
        media: 'Media and Entertainment',
        navigation: 'Navigation and Search',
        time: 'Time Management',
        connectivity: 'Connectivity',
        services: 'Digital Services',
        security: 'Security',
        
        // Topics
        makeCall: 'How to Make a Call',
        receiveCall: 'How to Pick Up a Call',
        saveContacts: 'How to Save Contacts',
        whatsappText: 'How to Text on WhatsApp',
        whatsappCalls: 'WhatsApp Calls & Video Calls',
        email: 'How to Use Email',
        installApp: 'How to Install an App',
        uninstallApp: 'How to Uninstall an App',
        deviceButtons: 'Device Buttons Guide',
        deviceButtonsDesc: 'Learn about the different buttons on your phone and their functions.',
        deviceButtonsStep1Title: 'Power Button',
        deviceButtonsStep1Desc: 'Located on the side of your phone. Press once to wake up or lock your phone. Press and hold to turn on/off your phone.',
        deviceButtonsStep2Title: 'Volume Buttons',
        deviceButtonsStep2Desc: 'Located on the side of your phone. Press + to increase volume, - to decrease volume. Also used for taking photos.',
        deviceButtonsStep3Title: 'Home Button',
        deviceButtonsStep3Desc: 'Located at the bottom of your phone. Press to return to the home screen. On newer phones, this may be a gesture instead of a physical button.',
        deviceButtonsStep4Title: 'Back Button',
        deviceButtonsStep4Desc: 'Located at the bottom of your phone. Press to go back to the previous screen. On newer phones, this may be a gesture instead of a physical button.',
        deviceButtonsTip1: 'Press and hold the power button to access emergency features and phone settings.',
        deviceButtonsTip2: 'Use volume buttons to adjust ringtone, media, and alarm volume separately.',
        deviceButtonsTip3: 'On newer phones, swipe up from the bottom to go home or back.',
        deviceButtonsIssue1Title: 'Phone Not Responding',
        deviceButtonsIssue1Desc: 'Press and hold the power button for 10 seconds to force restart your phone.',
        deviceButtonsIssue2Title: 'Volume Not Working',
        deviceButtonsIssue2Desc: 'Check if your phone is in silent mode by pressing the volume buttons and looking for the silent mode indicator.',
        photos: 'Photos & Gallery',
        youtube: 'How to Use YouTube',
        youtubeDesc: 'Learn how to watch videos, subscribe to channels, and manage your YouTube experience.',
        youtubeStep1Title: 'Open YouTube',
        youtubeStep1Desc: 'Find and tap the YouTube app icon on your home screen or app drawer.',
        youtubeStep2Title: 'Search for Videos',
        youtubeStep2Desc: 'Tap the search bar at the top and type what you want to watch.',
        youtubeStep3Title: 'Watch Videos',
        youtubeStep3Desc: 'Tap on a video to play it. Use the play/pause button to control playback.',
        youtubeStep4Title: 'Subscribe to Channels',
        youtubeStep4Desc: 'Tap the Subscribe button on any channel to get notified about new videos.',
        youtubeTip1: 'Double-tap the left or right side of the video to rewind or fast forward.',
        youtubeTip2: 'Tap the three dots menu to find options like save to playlist or share.',
        youtubeTip3: 'Enable autoplay to keep watching related videos automatically.',
        youtubeIssue1Title: 'Video Not Playing',
        youtubeIssue1Desc: 'Check your internet connection and try closing and reopening the app.',
        youtubeIssue2Title: 'Poor Video Quality',
        youtubeIssue2Desc: 'Tap the three dots menu, select Quality, and choose a higher resolution.',
        news: 'Getting News Online',
        maps: 'Using Google Maps',
        googleSearch: 'Google Search',
        googleSearchDesc: 'Learn how to effectively search for information using Google Search.',
        googleSearchStep1Title: 'Open Google',
        googleSearchStep1Desc: 'Find and tap the Google app icon or open your web browser and go to google.com.',
        googleSearchStep2Title: 'Type Your Search',
        googleSearchStep2Desc: 'Tap the search bar and type what you want to find. Be specific for better results.',
        googleSearchStep3Title: 'View Results',
        googleSearchStep3Desc: 'Scroll through the search results and tap on the most relevant link.',
        googleSearchStep4Title: 'Refine Search',
        googleSearchStep4Desc: 'Use filters like Images, News, or Videos to find specific types of content.',
        googleSearchTip1: 'Use quotation marks to search for exact phrases.',
        googleSearchTip2: 'Add site: before a website to search within that site.',
        googleSearchTip3: 'Use the microphone icon for voice search.',
        googleSearchIssue1Title: 'No Results Found',
        googleSearchIssue1Desc: 'Try using different keywords or check your spelling.',
        googleSearchIssue2Title: 'Slow Loading',
        googleSearchIssue2Desc: 'Check your internet connection and try refreshing the page.',
        assistant: 'Google Assistant',
        alarm: 'Setting Alarms',
        wifi: 'WiFi & Hotspot',
        wifiDesc: 'Learn how to connect to WiFi networks and use your phone as a mobile hotspot.',
        keyboard: 'Keyboard Language',
        payments: 'Online Payments',
        paymentsDesc: 'Learn how to make secure online payments using UPI, mobile wallets, and other digital payment methods.',
        paymentsStep1Title: 'Choose Payment App',
        paymentsStep1Desc: 'Install and open a payment app like Google Pay, PhonePe, or Paytm from the Play Store.',
        paymentsStep2Title: 'Link Bank Account',
        paymentsStep2Desc: 'Add your bank account details and verify your identity using your Aadhaar number or PAN.',
        paymentsStep3Title: 'Make Payment',
        paymentsStep3Desc: 'Enter the recipient\'s UPI ID or scan their QR code, enter the amount, and confirm the payment.',
        paymentsStep4Title: 'Verify Transaction',
        paymentsStep4Desc: 'Check the transaction status and save the payment receipt for future reference.',
        paymentsTip1: 'Always verify the recipient\'s details before making a payment.',
        paymentsTip2: 'Keep your UPI PIN and app passwords secure and never share them.',
        paymentsTip3: 'Enable transaction notifications to track your payments.',
        paymentsIssue1Title: 'Payment Failed',
        paymentsIssue1Desc: 'Check your internet connection and ensure you have sufficient balance in your account.',
        paymentsIssue2Title: 'Wrong UPI ID',
        paymentsIssue2Desc: 'Double-check the UPI ID before confirming the payment to avoid sending money to the wrong person.',
        rides: 'Booking Rides',
        ridesDesc: 'Uber and Ola apps to book rides. Learn how to use them.',
        ridesStep1Title: 'Open App',
        ridesStep1Desc: 'Open Uber or Ola app on your phone and sign in.',
        ridesStep2Title: 'Set Location',
        ridesStep2Desc: 'Enter your pickup location and destination, or use the map to select a location.',
        ridesStep3Title: 'Choose Ride Type',
        ridesStep3Desc: 'Select your preferred ride type (auto, mini, prime, etc.) and estimate the fare.',
        ridesStep4Title: 'Book Ride',
        ridesStep4Desc: 'Tap "Book" or "Confirm" to request a ride. Wait for the driver to accept your request.',
        ridesTip1: 'Use accurate pickup and drop-off points for better service.',
        ridesTip2: 'Before accepting a ride, check the driver\'s rating and vehicle details.',
        ridesTip3: 'Use the "Trip Share" feature to share your location with the driver.',
        ridesIssue1Title: 'No Driver Available',
        ridesIssue1Desc: 'Try again later or wait a few minutes before trying again.',
        ridesIssue2Title: 'Incorrect Location',
        ridesIssue2Desc: 'Make sure your pickup and drop-off points are correct on the map.',
        cybersecurity: 'Cybersecurity',
        cybersecurityDesc: 'Learn how to protect your phone and personal information from online threats.',
        cybersecurityStep1Title: 'Set Screen Lock',
        cybersecurityStep1Desc: 'Go to Settings > Security and set a PIN, pattern, or biometric lock for your phone.',
        cybersecurityStep2Title: 'Install Security App',
        cybersecurityStep2Desc: 'Download and install a reliable antivirus app from Play Store to protect against malware.',
        cybersecurityStep3Title: 'Regular Updates',
        cybersecurityStep3Desc: 'Keep your phone software and apps updated to get the latest security patches.',
        cybersecurityStep4Title: 'Secure Accounts',
        cybersecurityStep4Desc: 'Use strong passwords for your important accounts and enable two-factor authentication.',
        cybersecurityTip1: 'Never share your password or OTP with anyone, even if they claim to be from your bank.',
        cybersecurityTip2: 'Be cautious when clicking on links in messages or emails from unknown sources.',
        cybersecurityTip3: 'Regularly back up your important data to cloud storage or external devices.',
        cybersecurityIssue1Title: 'Suspicious Activity',
        cybersecurityIssue1Desc: 'If you see unusual activity, immediately change your password and contact your bank.',
        cybersecurityIssue2Title: 'Unknown Apps',
        cybersecurityIssue2Desc: 'Regularly check your installed apps and uninstall any you don\'t remember installing.',
        
        // Common
        previousTopic: 'Previous Topic',
        nextTopic: 'Next Topic',
        instructions: 'Step-by-Step Instructions',
        tips: 'Helpful Tips',
        commonIssues: 'Common Issues and Solutions',
        videoPlaceholder: 'Video tutorial will be available soon',
        
        // About Us Page
        aboutTitle: 'About MitraYug',
        aboutSubtitle: 'Empowering Senior Citizens with Digital Literacy',
        ourMission: 'Our Mission',
        missionText: 'MitraYug is dedicated to making technology accessible to senior citizens by providing easy-to-understand digital literacy resources. We believe that everyone, regardless of age, should have the opportunity to benefit from modern technology.',
        ourVision: 'Our Vision',
        visionText: 'We envision a world where senior citizens are confident and comfortable using digital devices and services, enabling them to stay connected with loved ones, access information, and participate in the digital economy.',
        ourValues: 'Our Values',
        value1Title: 'Empathy',
        value1Text: 'We understand the unique challenges faced by senior citizens and design our resources accordingly.',
        value2Title: 'Education',
        value2Text: 'We believe in continuous learning and provide comprehensive, easy-to-follow tutorials.',
        value3Title: 'Community',
        value3Text: 'We foster a supportive learning environment where everyone can help each other grow.',
        value4Title: 'Trust',
        value4Text: 'We prioritize user safety and provide reliable, accurate information.',
        ourTeam: 'Our Team',
        team1Name: 'Dr. Priya Sharma',
        team1Role: 'Senior Educator',
        team2Name: 'Rahul Verma',
        team2Role: 'UI Designer',
        team3Name: 'Anita Patel',
        team3Role: 'Developer',
        getInvolved: 'Get Involved',
        involvedText: 'We\'re always looking for volunteers and partners who share our vision. Join us in making technology accessible to everyone.',
        contactUs: 'Contact Us',
        
        // All Topics Page
        allTopicsTitle: 'All Learning Topics',
        allTopicsDesc: 'Browse through all our digital literacy topics. Use the search bar to find specific topics.',
        searchPlaceholder: 'Search topics...',
        noResults: 'No topics found matching your search.',
        
        // Footer
        aboutText: 'MitraYug is dedicated to making technology accessible to everyone.',
        quickLinks: 'Quick Links',
        contact: 'Contact',
        email: 'Email: support@mitrayug.com',
        phone: 'Phone: +91 1234567890',
        copyright: '© 2025 MitraYug. All rights reserved.',
        
        // WhatsApp Text Messaging
        whatsappTextDesc: 'Learn how to send text messages on WhatsApp with this easy-to-follow guide.',
        whatsappStep1Title: 'Open WhatsApp',
        whatsappStep1Desc: 'Find and tap the WhatsApp icon on your home screen or app drawer.',
        whatsappStep2Title: 'Select a Contact',
        whatsappStep2Desc: 'Tap on the contact you want to message from your chat list, or tap the new chat icon to start a new conversation.',
        whatsappStep3Title: 'Type Your Message',
        whatsappStep3Desc: 'Type your message in the text box at the bottom of the screen.',
        whatsappStep4Title: 'Send the Message',
        whatsappStep4Desc: 'Tap the send button (paper plane icon) to send your message.',
        whatsappTip1: 'You can use emojis by tapping the smiley face icon next to the text box.',
        whatsappTip2: 'To send a voice message, hold and hold the microphone icon while speaking.',
        whatsappTip3: 'You can attach files, photos, or documents by tapping the paperclip icon.',
        whatsappIssue1Title: 'Message Not Sending',
        whatsappIssue1Desc: 'Check your internet connection and make sure you have sufficient data.',
        whatsappIssue2Title: 'Contact Not Found',
        whatsappIssue2Desc: 'Make sure the contact has WhatsApp installed and is using the correct phone number.',
        
        // WhatsApp Calls
        whatsappCallsDesc: 'Learn how to make voice and video calls on WhatsApp with this easy-to-follow guide.',
        whatsappCallStep1Title: 'Open WhatsApp',
        whatsappCallStep1Desc: 'Find and tap the WhatsApp icon on your home screen or app drawer.',
        whatsappCallStep2Title: 'Select a Contact',
        whatsappCallStep2Desc: 'Tap on the contact you want to call from your chat list.',
        whatsappCallStep3Title: 'Start the Call',
        whatsappCallStep3Desc: 'For voice calls, tap the phone icon. For video calls, tap the video camera icon.',
        whatsappCallStep4Title: 'End the Call',
        whatsappCallStep4Desc: 'Tap the red end call button to hang up when finished.',
        whatsappCallTip1: 'Make sure you have a stable internet connection for clear calls.',
        whatsappCallTip2: 'You can switch between voice and video calls during the call.',
        whatsappCallTip3: 'Use headphones for better audio quality and privacy.',
        whatsappCallIssue1Title: 'Poor Call Quality',
        whatsappCallIssue1Desc: 'Check your internet connection and try moving to an area with better network coverage.',
        whatsappCallIssue2Title: 'Camera Not Working',
        whatsappCallIssue2Desc: 'Make sure you\'ve granted camera permissions to WhatsApp in your phone settings.',
        
        // Email
        emailDesc: 'Learn how to send and receive emails with this easy-to-follow guide.',
        emailStep1Title: 'Open Email App',
        emailStep1Desc: 'Find and tap the Gmail or Email app icon on your home screen or app drawer.',
        emailStep2Title: 'Compose New Email',
        emailStep2Desc: 'Tap the compose or new email button (usually a pencil or plus icon).',
        emailStep3Title: 'Fill Email Details',
        emailStep3Desc: 'Enter the recipient\'s email address, subject, and your message in the appropriate fields.',
        emailStep4Title: 'Send Email',
        emailStep4Desc: 'Tap the send button (paper plane icon) to send your email.',
        emailTip1: 'You can attach files by tapping the paperclip icon before sending.',
        emailTip2: 'To reply to an email, tap the reply button in the email thread.',
        emailTip3: 'You can organize emails into folders for better management.',
        emailIssue1Title: 'Email Not Sending',
        emailIssue1Desc: 'Check your internet connection and make sure you\'ve entered the recipient\'s email address correctly.',
        emailIssue2Title: 'Can\'t Find Emails',
        emailIssue2Desc: 'Use the search bar at the top of the app to find specific emails by sender or subject.',
        
        // App Installation
        installApp: 'How to Install an App',
        installAppDesc: 'Learn how to install new apps on your phone with this easy-to-follow guide.',
        installAppStep1Title: 'Open App Store',
        installAppStep1Desc: 'Find and tap the Play Store (Android) or App Store (iPhone) icon on your home screen.',
        installAppStep2Title: 'Search for App',
        installAppStep2Desc: 'Tap the search bar at the top and type the name of the app you want to install.',
        installAppStep3Title: 'Select App',
        installAppStep3Desc: 'Tap on the app from the search results to view its details.',
        installAppStep4Title: 'Install App',
        installAppStep4Desc: 'Tap the Install or Get button to download and install the app.',
        installAppTip1: 'Make sure you have enough storage space on your phone before installing.',
        installAppTip2: 'Read the app\'s description and reviews before installing.',
        installAppTip3: 'Keep your phone connected to WiFi for faster downloads.',
        installAppIssue1Title: 'Not Enough Storage',
        installAppIssue1Desc: 'Delete unused apps or files to free up storage space.',
        installAppIssue2Title: 'Installation Failed',
        installAppIssue2Desc: 'Check your internet connection and try again. If the problem persists, restart your phone.',
        
        // App Uninstallation
        uninstallApp: 'How to Uninstall an App',
        uninstallAppDesc: 'Learn how to remove apps from your phone with this easy-to-follow guide.',
        uninstallAppStep1Title: 'Open Settings',
        uninstallAppStep1Desc: 'Find and tap the Settings app on your home screen or app drawer.',
        uninstallAppStep2Title: 'Go to Apps',
        uninstallAppStep2Desc: 'Scroll down and tap on Apps or Applications in the Settings menu.',
        uninstallAppStep3Title: 'Select App',
        uninstallAppStep3Desc: 'Find and tap on the app you want to uninstall from the list.',
        uninstallAppStep4Title: 'Uninstall App',
        uninstallAppStep4Desc: 'Tap the Uninstall button and confirm when prompted.',
        uninstallAppTip1: 'Some system apps cannot be uninstalled as they are essential for your phone.',
        uninstallAppTip2: 'Uninstalling an app will remove all its data from your phone.',
        uninstallAppTip3: 'You can reinstall apps later from the app store if needed.',
        uninstallAppIssue1Title: 'Can\'t Find App',
        uninstallAppIssue1Desc: 'Use the search bar in Settings to find the app you want to uninstall.',
        uninstallAppIssue2Title: 'Uninstall Button Grayed Out',
        uninstallAppIssue2Desc: 'This means the app is a system app and cannot be uninstalled.',
        assistantDesc: "Learn how to use Google Assistant to get help with tasks using voice commands.",
        assistantStep1Title: "Open Assistant",
        assistantStep1Desc: "Say \"Hey Google\" or tap the Assistant icon on your home screen.",
        assistantStep2Title: "Ask Questions",
        assistantStep2Desc: "Ask questions or give commands like \"What's the weather?\" or \"Set an alarm for 7 AM\".",
        assistantStep3Title: "Get Responses",
        assistantStep3Desc: "Listen to the Assistant's response or read the text on screen.",
        assistantStep4Title: "Follow Up",
        assistantStep4Desc: "Ask follow-up questions or give new commands without saying \"Hey Google\" again.",
        assistantTip1: "Use \"Hey Google\" to wake up the Assistant from any screen.",
        assistantTip2: "Try asking for translations, calculations, or directions.",
        assistantTip3: "You can control your smart home devices through the Assistant.",
        assistantIssue1Title: "Not Responding",
        assistantIssue1Desc: "Check your internet connection and make sure the microphone is working.",
        assistantIssue2Title: "Wrong Language",
        assistantIssue2Desc: "Go to Assistant settings to change the language to your preferred one.",
        alarmDesc: "Learn how to set and manage alarms on your phone.",
        alarmStep1Title: "Open Clock App",
        alarmStep1Desc: "Find and tap the Clock app icon on your home screen or app drawer.",
        alarmStep2Title: "Add New Alarm",
        alarmStep2Desc: "Tap the + button or \"Add Alarm\" to create a new alarm.",
        alarmStep3Title: "Set Time",
        alarmStep3Desc: "Use the time picker to set your desired alarm time.",
        alarmStep4Title: "Save Alarm",
        alarmStep4Desc: "Tap \"Save\" or \"Done\" to set the alarm. You can enable/disable it using the switch.",
        alarmTip1: "Set multiple alarms for different times of the day.",
        alarmTip2: "Choose different sounds for different alarms.",
        alarmTip3: "Use the snooze feature to delay the alarm by a few minutes.",
        alarmIssue1Title: "Alarm Not Sounding",
        alarmIssue1Desc: "Check if your phone is in silent mode and the volume is turned up.",
        alarmIssue2Title: "Wrong Time",
        alarmIssue2Desc: "Make sure your phone's time and timezone settings are correct.",
        
        // Help Center Page
        helpCenterTitle: 'Help Center',
        helpCenterDesc: 'Find answers to common questions and get support when you need it.',
        faqTitle: 'Frequently Asked Questions',
        faqStartLearning: 'How do I start learning?',
        faqStartLearningAnswer: 'Start by choosing a topic from the home page that interests you. Each topic has step-by-step instructions and video tutorials to help you learn.',
        faqUseMitraYug: 'Can I use MitraYug on my phone?',
        faqUseMitraYugAnswer: 'Yes! MitraYug is designed to work on all devices including smartphones, tablets, and computers. The interface is optimized for easy use on any screen size.',
        faqVoiceAssistance: 'How do I use the voice assistance feature?',
        faqVoiceAssistanceAnswer: 'Click the speaker icon in the top navigation bar to enable voice assistance. Then, click on any text to have it read aloud to you.',
        faqMoreHelp: 'What if I need more help?',
        faqMoreHelpAnswer: 'You can contact our support team using the form below. We\'re here to help and will respond to your questions as soon as possible.',
        yourName: 'Your Name',
        phoneNumber: 'Phone Number',
        yourQuestion: 'Your Question',
        sendMessage: 'Send Message',
    },
    hi: {
        // Navigation
        home: 'होम',
        help: 'सहायता',
        allTopics: 'सभी विषय',
        aboutUs: 'हमारे बारे में',
        
        // Accessibility
        contrastToggle: 'उच्च कंट्रास्ट मोड टॉगल करें',
        fontSizeToggle: 'बड़ा टेक्स्ट टॉगल करें',
        voiceToggle: 'वॉइस सहायता टॉगल करें',
        languageToggle: 'भाषा टॉगल करें',
        
        // Homepage
        welcomeTitle: 'मित्रयुग - डिजिटल साक्षरता के माध्यम से पीढ़ियों को जोड़ना',
        welcomeText: 'मित्रयुग में आपका स्वागत है, डिजिटल कौशल सीखने के लिए आपका मित्रवत मार्गदर्शक। हम तकनीक को सरल और सुलभ बनाते हैं।',
        startLearning: 'सीखना शुरू करें',
        
        // Topic Categories
        basicPhone: 'बेसिक फोन ऑपरेशन्स',
        messaging: 'मैसेजिंग और संचार',
        apps: 'ऐप्स और डिवाइस प्रबंधन',
        media: 'मीडिया और मनोरंजन',
        navigation: 'नेविगेशन और खोज',
        time: 'समय प्रबंधन',
        connectivity: 'कनेक्टिविटी',
        services: 'डिजिटल सेवाएं',
        security: 'सुरक्षा',
        
        // Topics
        makeCall: 'कॉल कैसे करें',
        receiveCall: 'कॉल कैसे रिसीव करें',
        saveContacts: 'कॉन्टैक्ट्स कैसे सेव करें',
        whatsappText: 'व्हाट्सएप पर मैसेज कैसे करें',
        whatsappCalls: 'व्हाट्सएप कॉल्स और वीडियो कॉल्स',
        email: 'ईमेल कैसे करें',
        installApp: 'ऐप कैसे इंस्टॉल करें',
        uninstallApp: 'ऐप कैसे अनइंस्टॉल करें',
        deviceButtons: 'डिवाइस बटन्स गाइड',
        deviceButtonsDesc: 'अपने फोन के विभिन्न बटनों और उनके कार्यों के बारे में जानें।',
        deviceButtonsStep1Title: 'पावर बटन',
        deviceButtonsStep1Desc: 'फोन के किनारे स्थित। फोन को जगाने या लॉक करने के लिए एक बार दबाएं। फोन को चालू/बंद करने के लिए दबाकर रखें।',
        deviceButtonsStep2Title: 'वॉल्यूम बटन',
        deviceButtonsStep2Desc: 'फोन के किनारे स्थित। वॉल्यूम बढ़ाने के लिए + दबाएं, कम करने के लिए - दबाएं। फोटो लेने के लिए भी उपयोग किया जाता है।',
        deviceButtonsStep3Title: 'होम बटन',
        deviceButtonsStep3Desc: 'फोन के नीचे स्थित। होम स्क्रीन पर जाने के लिए दबाएं। नए फोनों में, यह भौतिक बटन के बजाय जेस्चर हो सकता है।',
        deviceButtonsStep4Title: 'बैक बटन',
        deviceButtonsStep4Desc: 'फोन के नीचे स्थित। पिछली स्क्रीन पर जाने के लिए दबाएं। नए फोनों में, यह भौतिक बटन के बजाय जेस्चर हो सकता है।',
        deviceButtonsTip1: 'आपातकालीन सुविधाओं और फोन सेटिंग्स तक पहुंचने के लिए पावर बटन को दबाकर रखें।',
        deviceButtonsTip2: 'रिंगटोन, मीडिया और अलार्म वॉल्यूम को अलग-अलग समायोजित करने के लिए वॉल्यूम बटन का उपयोग करें।',
        deviceButtonsTip3: 'नए फोनों में, होम या बैक जाने के लिए नीचे से ऊपर स्वाइप करें।',
        deviceButtonsIssue1Title: 'फोन प्रतिक्रिया नहीं दे रहा',
        deviceButtonsIssue1Desc: 'फोन को बलपूर्वक रीस्टार्ट करने के लिए पावर बटन को 10 सेकंड तक दबाकर रखें।',
        deviceButtonsIssue2Title: 'वॉल्यूम काम नहीं कर रहा',
        deviceButtonsIssue2Desc: 'वॉल्यूम बटन दबाकर और साइलेंट मोड संकेतक देखकर जांचें कि क्या आपका फोन साइलेंट मोड में है।',
        photos: 'फोटोज और गैलरी',
        youtube: 'यूट्यूब कैसे इस्तेमाल करें',
        youtubeDesc: 'वीडियो देखना, चैनल्स को सब्सक्राइब करना और अपना यूट्यूब अनुभव प्रबंधित करना सीखें।',
        youtubeStep1Title: 'यूट्यूब खोलें',
        youtubeStep1Desc: 'अपने होम स्क्रीन या ऐप ड्रॉअर पर यूट्यूब ऐप आइकन को ढूंढें और टैप करें।',
        youtubeStep2Title: 'वीडियो खोजें',
        youtubeStep2Desc: 'शीर्ष पर सर्च बार को टैप करें और जो देखना चाहते हैं वह टाइप करें।',
        youtubeStep3Title: 'वीडियो देखें',
        youtubeStep3Desc: 'वीडियो को चलाने के लिए उस पर टैप करें। प्ले/पॉज़ बटन का उपयोग करके प्लेबैक को नियंत्रित करें।',
        youtubeStep4Title: 'चैनल्स को सब्सक्राइब करें',
        youtubeStep4Desc: 'नए वीडियो के बारे में सूचनाएं प्राप्त करने के लिए किसी भी चैनल पर सब्सक्राइब बटन को टैप करें।',
        youtubeTip1: 'वीडियो को रिवाइंड या फास्ट फॉरवर्ड करने के लिए वीडियो के बाएं या दाएं तरफ डबल-टैप करें।',
        youtubeTip2: 'प्लेलिस्ट में सेव करने या शेयर करने जैसे विकल्प खोजने के लिए तीन डॉट्स मेनू को टैप करें।',
        youtubeTip3: 'संबंधित वीडियो को स्वचालित रूप से देखते रहने के लिए ऑटोप्ले सक्षम करें।',
        youtubeIssue1Title: 'वीडियो नहीं चल रहा',
        youtubeIssue1Desc: 'अपना इंटरनेट कनेक्शन जांचें और ऐप को बंद करके फिर से खोलने का प्रयास करें।',
        youtubeIssue2Title: 'खराब वीडियो गुणवत्ता',
        youtubeIssue2Desc: 'तीन डॉट्स मेनू को टैप करें, क्वालिटी चुनें, और उच्च रिज़ॉल्यूशन चुनें।',
        news: 'ऑनलाइन न्यूज कैसे देखें',
        maps: 'गूगल मैप्स का उपयोग',
        googleSearch: 'गूगल सर्च',
        googleSearchDesc: 'गूगल सर्च का उपयोग करके जानकारी खोजना सीखें।',
        googleSearchStep1Title: 'गूगल खोलें',
        googleSearchStep1Desc: 'गूगल ऐप आइकन को ढूंढें और टैप करें या अपने वेब ब्राउज़र में जाकर google.com खोलें।',
        googleSearchStep2Title: 'सर्च टाइप करें',
        googleSearchStep2Desc: 'सर्च बार में टैप करें और जो खोजना चाहते हैं वह टाइप करें। बेहतर परिणामों के लिए विशिष्ट रहें।',
        googleSearchStep3Title: 'परिणाम देखें',
        googleSearchStep3Desc: 'सर्च परिणामों को स्क्रॉल करें और सबसे प्रासंगिक लिंक पर टैप करें।',
        googleSearchStep4Title: 'सर्च को परिष्कृत करें',
        googleSearchStep4Desc: 'विशिष्ट प्रकार की सामग्री खोजने के लिए छवियां, समाचार या वीडियो जैसे फ़िल्टर का उपयोग करें।',
        googleSearchTip1: 'सटीक वाक्यांश खोजने के लिए उद्धरण चिह्नों का उपयोग करें।',
        googleSearchTip2: 'किसी वेबसाइट के भीतर खोजने के लिए वेबसाइट से पहले site: जोड़ें।',
        googleSearchTip3: 'वॉइस सर्च के लिए माइक्रोफ़ोन आइकन का उपयोग करें।',
        googleSearchIssue1Title: 'कोई परिणाम नहीं मिला',
        googleSearchIssue1Desc: 'विभिन्न कीवर्ड का उपयोग करें या अपनी स्पेलिंग जांचें।',
        googleSearchIssue2Title: 'धीमी लोडिंग',
        googleSearchIssue2Desc: 'अपना इंटरनेट कनेक्शन जांचें और पेज को रीफ्रेश करें।',
        assistant: 'गूगल असिस्टेंट',
        alarm: 'अलार्म सेट करना',
        wifi: 'WiFi और हॉटस्पॉट',
        wifiDesc: 'WiFi नेटवर्क से कनेक्ट करना और अपने फोन को मोबाइल हॉटस्पॉट के रूप में उपयोग करना सीखें।',
        keyboard: 'कीबोर्ड भाषा',
        payments: 'ऑनलाइन भुगतान',
        paymentsDesc: 'UPI, मोबाइल वॉलेट और अन्य डिजिटल भुगतान विधियों का उपयोग करके सुरक्षित ऑनलाइन भुगतान करना सीखें।',
        paymentsStep1Title: 'भुगतान ऐप चुनें',
        paymentsStep1Desc: 'Play Store से Google Pay, PhonePe या Paytm जैसा भुगतान ऐप इंस्टॉल और खोलें।',
        paymentsStep2Title: 'बैंक खाता लिंक करें',
        paymentsStep2Desc: 'अपने आधार नंबर या PAN का उपयोग करके अपने बैंक खाते का विवरण जोड़ें और अपनी पहचान सत्यापित करें।',
        paymentsStep3Title: 'भुगतान करें',
        paymentsStep3Desc: 'प्राप्तकर्ता का UPI ID दर्ज करें या उनका QR कोड स्कैन करें, राशि दर्ज करें और भुगतान की पुष्टि करें।',
        paymentsStep4Title: 'लेनदेन सत्यापित करें',
        paymentsStep4Desc: 'लेनदेन की स्थिति जांचें और भविष्य के संदर्भ के लिए भुगतान रसीद सहेजें।',
        paymentsTip1: 'भुगतान करने से पहले प्राप्तकर्ता का विवरण सत्यापित करें।',
        paymentsTip2: 'अपने UPI PIN और ऐप पासवर्ड को सुरक्षित रखें और कभी भी साझा न करें।',
        paymentsTip3: 'अपने भुगतान को ट्रैक करने के लिए लेनदेन सूचनाएं सक्षम करें।',
        paymentsIssue1Title: 'भुगतान विफल',
        paymentsIssue1Desc: 'अपना इंटरनेट कनेक्शन जांचें और सुनिश्चित करें कि आपके खाते में पर्याप्त शेष राशि है।',
        paymentsIssue2Title: 'गलत UPI ID',
        paymentsIssue2Desc: 'गलत व्यक्ति को पैसा भेजने से बचने के लिए भुगतान की पुष्टि करने से पहले UPI ID की दोबारा जांच करें।',
        rides: 'राइड बुक करना',
        ridesDesc: 'Uber और Ola जैसे लोकप्रिय राइड-हेलिंग ऐप्स का उपयोग करके राइड बुक करना सीखें।',
        ridesStep1Title: 'ऐप खोलें',
        ridesStep1Desc: 'अपने फोन पर Uber या Ola ऐप खोलें और अपने खाते में साइन इन करें।',
        ridesStep2Title: 'स्थान सेट करें',
        ridesStep2Desc: 'अपना पिकअप स्थान और गंतव्य दर्ज करें, या स्थान चुनने के लिए मैप का उपयोग करें।',
        ridesStep3Title: 'राइड चुनें',
        ridesStep3Desc: 'अपनी पसंदीदा राइड प्रकार चुनें (ऑटो, मिनी, प्राइम, आदि) और अनुमानित किराया देखें।',
        ridesStep4Title: 'राइड बुक करें',
        ridesStep4Desc: 'राइड का अनुरोध करने के लिए "बुक" या "कन्फर्म" टैप करें। ड्राइवर के अनुरोध स्वीकार करने का इंतजार करें।',
        ridesTip1: 'सटीक पिकअप और ड्रॉप-ऑफ पॉइंट के लिए लोकेशन सेवाएं सक्षम करें।',
        ridesTip2: 'राइड स्वीकार करने से पहले ड्राइवर की रेटिंग और वाहन विवरण जांचें।',
        ridesTip3: 'अपने परिवार को अपना स्थान बताने के लिए "ट्रिप शेयर" सुविधा का उपयोग करें।',
        ridesIssue1Title: 'कोई ड्राइवर उपलब्ध नहीं',
        ridesIssue1Desc: 'नॉन-पीक घंटों में प्रयास करें या कुछ मिनट प्रतीक्षा करें और फिर से प्रयास करें।',
        ridesIssue2Title: 'गलत स्थान',
        ridesIssue2Desc: 'अपना सटीक पिकअप या ड्रॉप-ऑफ पॉइंट चुनने के लिए मैप का उपयोग करें।',
        cybersecurity: 'साइबर सुरक्षा',
        cybersecurityDesc: 'अपने फोन और व्यक्तिगत जानकारी को ऑनलाइन खतरों से बचाना सीखें।',
        cybersecurityStep1Title: 'स्क्रीन लॉक सेट करें',
        cybersecurityStep1Desc: 'सेटिंग्स > सुरक्षा में जाएं और अपने फोन के लिए PIN, पैटर्न या बायोमेट्रिक लॉक सेट करें।',
        cybersecurityStep2Title: 'सुरक्षा ऐप इंस्टॉल करें',
        cybersecurityStep2Desc: 'मैलवेयर से बचाने के लिए Play Store से विश्वसनीय एंटीवायरस ऐप डाउनलोड और इंस्टॉल करें।',
        cybersecurityStep3Title: 'नियमित अपडेट करें',
        cybersecurityStep3Desc: 'नवीनतम सुरक्षा पैच प्राप्त करने के लिए अपने फोन के सॉफ्टवेयर और ऐप्स को अपडेट रखें।',
        cybersecurityStep4Title: 'खातों को सुरक्षित करें',
        cybersecurityStep4Desc: 'अपने महत्वपूर्ण खातों के लिए मजबूत पासवर्ड का उपयोग करें और दो-कारक प्रमाणीकरण सक्षम करें।',
        cybersecurityTip1: 'अपने पासवर्ड या OTP कभी भी किसी के साथ साझा न करें, भले ही वे आपके बैंक से होने का दावा करें।',
        cybersecurityTip2: 'अज्ञात स्रोतों से आने वाले संदेशों या ईमेल में लिंक पर क्लिक करते समय सावधान रहें।',
        cybersecurityTip3: 'अपने महत्वपूर्ण डेटा को नियमित रूप से क्लाउड स्टोरेज या बाहरी उपकरणों में बैकअप करें।',
        cybersecurityIssue1Title: 'संदिग्ध गतिविधि',
        cybersecurityIssue1Desc: 'यदि आप असामान्य गतिविधि देखते हैं, तो तुरंत अपने पासवर्ड बदलें और अपने बैंक से संपर्क करें।',
        cybersecurityIssue2Title: 'अज्ञात ऐप्स',
        cybersecurityIssue2Desc: 'नियमित रूप से अपने इंस्टॉल किए गए ऐप्स की जांच करें और जिन्हें आप इंस्टॉल करना याद नहीं करते उन्हें अनइंस्टॉल करें।',
        
        // Common
        previousTopic: 'पिछला विषय',
        nextTopic: 'अगला विषय',
        instructions: 'चरण-दर-चरण निर्देश',
        tips: 'सहायक टिप्स',
        commonIssues: 'सामान्य समस्याएं और समाधान',
        videoPlaceholder: 'वीडियो ट्यूटोरियल जल्द ही उपलब्ध होगा',
        
        // About Us Page
        aboutTitle: 'मित्रयुग के बारे में',
        aboutSubtitle: 'वरिष्ठ नागरिकों को डिजिटल साक्षरता से सशक्त बनाना',
        ourMission: 'हमारा मिशन',
        missionText: 'मित्रयुग वरिष्ठ नागरिकों के लिए आसानी से समझने योग्य डिजिटल साक्षरता संसाधन प्रदान करके तकनीक को सुलभ बनाने के लिए समर्पित है। हम मानते हैं कि उम्र की परवाह किए बिना सभी को आधुनिक तकनीक का लाभ उठाने का अवसर मिलना चाहिए।',
        ourVision: 'हमारी दृष्टि',
        visionText: 'हम एक ऐसी दुनिया की कल्पना करते हैं जहां वरिष्ठ नागरिक डिजिटल उपकरणों और सेवाओं का उपयोग करने में आत्मविश्वासी और सहज महसूस करते हैं, जिससे वे अपने प्रियजनों से जुड़े रह सकते हैं, जानकारी तक पहुंच सकते हैं और डिजिटल अर्थव्यवस्था में भाग ले सकते हैं।',
        ourValues: 'हमारे मूल्य',
        value1Title: 'सहानुभूति',
        value1Text: 'हम वरिष्ठ नागरिकों के सामने आने वाली विशिष्ट चुनौतियों को समझते हैं और उसी के अनुसार अपने संसाधनों को डिज़ाइन करते हैं।',
        value2Title: 'शिक्षा',
        value2Text: 'हम निरंतर सीखने में विश्वास करते हैं और व्यापक, आसानी से समझने योग्य ट्यूटोरियल प्रदान करते हैं।',
        value3Title: 'समुदाय',
        value3Text: 'हम एक सहायक सीखने का वातावरण बनाते हैं जहां सभी एक-दूसरे की मदद कर सकते हैं।',
        value4Title: 'विश्वास',
        value4Text: 'हम उपयोगकर्ता सुरक्षा को प्राथमिकता देते हैं और विश्वसनीय, सटीक जानकारी प्रदान करते हैं।',
        ourTeam: 'हमारी टीम',
        team1Name: 'डॉ. प्रिया शर्मा',
        team1Role: 'वरिष्ठ शिक्षक',
        team2Name: 'राहुल वर्मा',
        team2Role: 'यूआई डिजाइनर',
        team3Name: 'अनिता पटेल',
        team3Role: 'डेवलपर',
        getInvolved: 'शामिल हों',
        involvedText: 'हम हमेशा ऐसे स्वयंसेवकों और साझेदारों की तलाश में रहते हैं जो हमारी दृष्टि साझा करते हैं। तकनीक को सभी के लिए सुलभ बनाने में हमारा साथ दें।',
        contactUs: 'संपर्क करें',
        
        // All Topics Page
        allTopicsTitle: 'सभी सीखने के विषय',
        allTopicsDesc: 'हमारे सभी डिजिटल साक्षरता विषयों को ब्राउज़ करें। विशिष्ट विषयों को खोजने के लिए सर्च बार का उपयोग करें।',
        searchPlaceholder: 'विषय खोजें...',
        noResults: 'आपकी खोज से मेल खाने वाला कोई विषय नहीं मिला।',
        
        // Footer
        aboutText: 'मित्रयुग सभी के लिए तकनीक को सुलभ बनाने के लिए समर्पित है।',
        quickLinks: 'त्वरित लिंक्स',
        contact: 'संपर्क',
        email: 'ईमेल: support@mitrayug.com',
        phone: 'फोन: +91 1234567890',
        copyright: '© 2025 मित्रयुग। सर्वाधिकार सुरक्षित।',
        
        // WhatsApp Text Messaging
        whatsappTextDesc: 'व्हाट्सएप पर टेक्स्ट मैसेज भेजना सीखें इस आसान गाइड के साथ।',
        whatsappStep1Title: 'व्हाट्सएप खोलें',
        whatsappStep1Desc: 'अपने होम स्क्रीन या ऐप ड्रॉअर पर व्हाट्सएप आइकन को ढूंढें और टैप करें।',
        whatsappStep2Title: 'संपर्क चुनें',
        whatsappStep2Desc: 'अपनी चैट लिस्ट से संपर्क को टैप करें, या नई चैट शुरू करने के लिए नई चैट आइकन को टैप करें।',
        whatsappStep3Title: 'संदेश टाइप करें',
        whatsappStep3Desc: 'स्क्रीन के नीचे टेक्स्ट बॉक्स में अपना संदेश टाइप करें।',
        whatsappStep4Title: 'संदेश भेजें',
        whatsappStep4Desc: 'संदेश भेजने के लिए भेजें बटन (पेपर प्लेन आइकन) को टैप करें।',
        whatsappTip1: 'आप टेक्स्ट बॉक्स के बगल में स्माइली फेस आइकन को टैप करके इमोजी का उपयोग कर सकते हैं।',
        whatsappTip2: 'वॉइस मैसेज भेजने के लिए, बोलते समय माइक्रोफोन आइकन को दबाकर रखें।',
        whatsappTip3: 'आप पेपरक्लिप आइकन को टैप करके फाइलें, फोटो या दस्तावेज़ संलग्न कर सकते हैं।',
        whatsappIssue1Title: 'संदेश नहीं भेज रहा',
        whatsappIssue1Desc: 'अपना इंटरनेट कनेक्शन जांचें और सुनिश्चित करें कि आपके पास पर्याप्त डेटा है।',
        whatsappIssue2Title: 'संपर्क नहीं मिला',
        whatsappIssue2Desc: 'सुनिश्चित करें कि संपर्क के पास व्हाट्सएप इंस्टॉल है और सही फोन नंबर का उपयोग कर रहा है।',
        
        // WhatsApp Calls
        whatsappCallsDesc: 'व्हाट्सएप पर वॉइस और वीडियो कॉल करना सीखें इस आसान गाइड के साथ।',
        whatsappCallStep1Title: 'व्हाट्सएप खोलें',
        whatsappCallStep1Desc: 'अपने होम स्क्रीन या ऐप ड्रॉअर पर व्हाट्सएप आइकन को ढूंढें और टैप करें।',
        whatsappCallStep2Title: 'संपर्क चुनें',
        whatsappCallStep2Desc: 'अपनी चैट लिस्ट से संपर्क को टैप करें।',
        whatsappCallStep3Title: 'कॉल शुरू करें',
        whatsappCallStep3Desc: 'वॉइस कॉल के लिए फोन आइकन को टैप करें। वीडियो कॉल के लिए वीडियो कैमरा आइकन को टैप करें।',
        whatsappCallStep4Title: 'कॉल समाप्त करें',
        whatsappCallStep4Desc: 'समाप्त करने के लिए लाल एंड कॉल बटन को टैप करें।',
        whatsappCallTip1: 'स्पष्ट कॉल के लिए स्थिर इंटरनेट कनेक्शन सुनिश्चित करें।',
        whatsappCallTip2: 'कॉल के दौरान आप वॉइस और वीडियो कॉल के बीच स्विच कर सकते हैं।',
        whatsappCallTip3: 'बेहतर ऑडियो गुणवत्ता और गोपनीयता के लिए हेडफोन का उपयोग करें।',
        whatsappCallIssue1Title: 'खराब कॉल गुणवत्ता',
        whatsappCallIssue1Desc: 'अपना इंटरनेट कनेक्शन जांचें और बेहतर नेटवर्क कवरेज वाले क्षेत्र में जाने का प्रयास करें।',
        whatsappCallIssue2Title: 'कैमरा काम नहीं कर रहा',
        whatsappCallIssue2Desc: 'सुनिश्चित करें कि आपने अपने फोन सेटिंग्स में व्हाट्सएप को कैमरा अनुमति दी है।',
        
        // Email
        emailDesc: 'इस आसान गाइड के साथ ईमेल भेजना और प्राप्त करना सीखें।',
        emailStep1Title: 'ईमेल ऐप खोलें',
        emailStep1Desc: 'अपने होम स्क्रीन या ऐप ड्रॉअर पर जीमेल या ईमेल ऐप आइकन को ढूंढें और टैप करें।',
        emailStep2Title: 'नया ईमेल लिखें',
        emailStep2Desc: 'कंपोज़ या नया ईमेल बटन (आमतौर पर पेंसिल या प्लस आइकन) को टैप करें।',
        emailStep3Title: 'ईमेल विवरण भरें',
        emailStep3Desc: 'प्राप्तकर्ता का ईमेल पता, विषय और अपना संदेश उचित फ़ील्ड में दर्ज करें।',
        emailStep4Title: 'ईमेल भेजें',
        emailStep4Desc: 'अपना ईमेल भेजने के लिए भेजें बटन (पेपर प्लेन आइकन) को टैप करें।',
        emailTip1: 'भेजने से पहले पेपरक्लिप आइकन को टैप करके फ़ाइलें संलग्न कर सकते हैं।',
        emailTip2: 'ईमेल थ्रेड में रिप्लाई बटन को टैप करके ईमेल का जवाब दे सकते हैं।',
        emailTip3: 'बेहतर प्रबंधन के लिए ईमेल को फ़ोल्डर में व्यवस्थित कर सकते हैं।',
        emailIssue1Title: 'ईमेल नहीं भेज रहा',
        emailIssue1Desc: 'अपना इंटरनेट कनेक्शन जांचें और सुनिश्चित करें कि आपने प्राप्तकर्ता का ईमेल पता सही दर्ज किया है।',
        emailIssue2Title: 'ईमेल नहीं मिल रहा',
        emailIssue2Desc: 'प्रेषक या विषय के अनुसार विशिष्ट ईमेल खोजने के लिए ऐप के शीर्ष पर सर्च बार का उपयोग करें।',
        
        // App Installation
        installApp: 'ऐप कैसे इंस्टॉल करें',
        installAppDesc: 'इस आसान गाइड के साथ अपने फोन पर नए ऐप इंस्टॉल करना सीखें।',
        installAppStep1Title: 'ऐप स्टोर खोलें',
        installAppStep1Desc: 'अपनी होम स्क्रीन पर Play Store (Android) या App Store (iPhone) आइकन को ढूंढें और टैप करें।',
        installAppStep2Title: 'ऐप खोजें',
        installAppStep2Desc: 'शीर्ष पर सर्च बार को टैप करें और जिस ऐप को इंस्टॉल करना चाहते हैं उसका नाम टाइप करें।',
        installAppStep3Title: 'ऐप चुनें',
        installAppStep3Desc: 'सर्च रिजल्ट से ऐप को टैप करके उसकी जानकारी देखें।',
        installAppStep4Title: 'ऐप इंस्टॉल करें',
        installAppStep4Desc: 'ऐप को डाउनलोड और इंस्टॉल करने के लिए Install या Get बटन को टैप करें।',
        installAppTip1: 'इंस्टॉल करने से पहले सुनिश्चित करें कि आपके फोन में पर्याप्त स्टोरेज स्पेस है।',
        installAppTip2: 'इंस्टॉल करने से पहले ऐप का विवरण और समीक्षाएं पढ़ें।',
        installAppTip3: 'तेज डाउनलोड के लिए अपने फोन को WiFi से जुड़ा रखें।',
        installAppIssue1Title: 'पर्याप्त स्टोरेज नहीं',
        installAppIssue1Desc: 'स्टोरेज स्पेस बनाने के लिए अनावश्यक ऐप या फाइलें हटाएं।',
        installAppIssue2Title: 'इंस्टॉलेशन विफल',
        installAppIssue2Desc: 'अपना इंटरनेट कनेक्शन जांचें और फिर से कोशिश करें। यदि समस्या बनी रहती है, तो अपना फोन रीस्टार्ट करें।',
        
        // App Uninstallation
        uninstallApp: 'ऐप कैसे अनइंस्टॉल करें',
        uninstallAppDesc: 'इस आसान गाइड के साथ अपने फोन से ऐप हटाना सीखें।',
        uninstallAppStep1Title: 'सेटिंग्स खोलें',
        uninstallAppStep1Desc: 'अपने होम स्क्रीन या ऐप ड्रॉअर पर सेटिंग्स ऐप को ढूंढें और टैप करें।',
        uninstallAppStep2Title: 'ऐप्स पर जाएं',
        uninstallAppStep2Desc: 'सेटिंग्स मेनू में नीचे स्क्रॉल करें और ऐप्स या एप्लिकेशन्स पर टैप करें।',
        uninstallAppStep3Title: 'ऐप चुनें',
        uninstallAppStep3Desc: 'लिस्ट से जिस ऐप को अनइंस्टॉल करना चाहते हैं उसे ढूंढें और टैप करें।',
        uninstallAppStep4Title: 'ऐप अनइंस्टॉल करें',
        uninstallAppStep4Desc: 'अनइंस्टॉल बटन को टैप करें और पूछे जाने पर पुष्टि करें।',
        uninstallAppTip1: 'कुछ सिस्टम ऐप अनइंस्टॉल नहीं किए जा सकते क्योंकि वे आपके फोन के लिए आवश्यक हैं।',
        uninstallAppTip2: 'ऐप अनइंस्टॉल करने से उसका सारा डेटा आपके फोन से हट जाएगा।',
        uninstallAppTip3: 'आवश्यकता पड़ने पर आप बाद में ऐप स्टोर से ऐप को फिर से इंस्टॉल कर सकते हैं।',
        uninstallAppIssue1Title: 'ऐप नहीं मिल रहा',
        uninstallAppIssue1Desc: 'जिस ऐप को अनइंस्टॉल करना चाहते हैं उसे खोजने के लिए सेटिंग्स में सर्च बार का उपयोग करें।',
        uninstallAppIssue2Title: 'अनइंस्टॉल बटन धूमिल है',
        uninstallAppIssue2Desc: 'इसका मतलब है कि यह एक सिस्टम ऐप है और इसे अनइंस्टॉल नहीं किया जा सकता।',
        assistantDesc: "वॉइस कमांड का उपयोग करके कार्यों में मदद पाने के लिए गूगल असिस्टेंट का उपयोग करना सीखें।",
        assistantStep1Title: "असिस्टेंट खोलें",
        assistantStep1Desc: "\"Hey Google\" कहें या अपने होम स्क्रीन पर असिस्टेंट आइकन को टैप करें।",
        assistantStep2Title: "प्रश्न पूछें",
        assistantStep2Desc: "प्रश्न पूछें या कमांड दें जैसे \"मौसम कैसा है?\" या \"सुबह 7 बजे के लिए अलार्म सेट करें\"।",
        assistantStep3Title: "प्रतिक्रिया प्राप्त करें",
        assistantStep3Desc: "असिस्टेंट की प्रतिक्रिया सुनें या स्क्रीन पर टेक्स्ट पढ़ें।",
        assistantStep4Title: "अनुवर्ती प्रश्न",
        assistantStep4Desc: "\"Hey Google\" कहे बिना अनुवर्ती प्रश्न पूछें या नए कमांड दें।",
        assistantTip1: "किसी भी स्क्रीन से असिस्टेंट को जगाने के लिए \"Hey Google\" का उपयोग करें।",
        assistantTip2: "अनुवाद, गणना या दिशा-निर्देश के लिए पूछने का प्रयास करें।",
        assistantTip3: "आप असिस्टेंट के माध्यम से अपने स्मार्ट होम डिवाइस को नियंत्रित कर सकते हैं।",
        assistantIssue1Title: "प्रतिक्रिया नहीं दे रहा",
        assistantIssue1Desc: "अपना इंटरनेट कनेक्शन जांचें और सुनिश्चित करें कि माइक्रोफोन काम कर रहा है।",
        assistantIssue2Title: "गलत भाषा",
        assistantIssue2Desc: "अपनी पसंदीदा भाषा में बदलने के लिए असिस्टेंट सेटिंग्स में जाएं।",
        alarmDesc: "अपने फोन पर अलार्म सेट करना और प्रबंधित करना सीखें।",
        alarmStep1Title: "क्लॉक ऐप खोलें",
        alarmStep1Desc: "अपने होम स्क्रीन या ऐप ड्रॉअर पर क्लॉक ऐप आइकन को ढूंढें और टैप करें।",
        alarmStep2Title: "नया अलार्म जोड़ें",
        alarmStep2Desc: "नया अलार्म बनाने के लिए + बटन या \"Add Alarm\" को टैप करें।",
        alarmStep3Title: "समय सेट करें",
        alarmStep3Desc: "अपना वांछित अलार्म समय सेट करने के लिए टाइम पिकर का उपयोग करें।",
        alarmStep4Title: "अलार्म सेव करें",
        alarmStep4Desc: "अलार्म सेट करने के लिए \"Save\" या \"Done\" को टैप करें। आप स्विच का उपयोग करके इसे सक्षम/अक्षम कर सकते हैं।",
        alarmTip1: "दिन के विभिन्न समय के लिए कई अलार्म सेट करें।",
        alarmTip2: "विभिन्न अलार्म के लिए अलग-अलग ध्वनियां चुनें।",
        alarmTip3: "अलार्म को कुछ मिनटों के लिए विलंबित करने के लिए स्नूज़ सुविधा का उपयोग करें।",
        alarmIssue1Title: "अलार्म नहीं बज रहा",
        alarmIssue1Desc: "जांचें कि क्या आपका फोन साइलेंट मोड में है और वॉल्यूम बढ़ा हुआ है।",
        alarmIssue2Title: "गलत समय",
        alarmIssue2Desc: "सुनिश्चित करें कि आपके फोन का समय और टाइमज़ोन सेटिंग्स सही हैं।",
        
        // Help Center Page
        helpCenterTitle: 'सहायता केंद्र',
        helpCenterDesc: 'सामान्य प्रश्नों के उत्तर पाएं और जब आपको जरूरत हो तब सहायता प्राप्त करें।',
        faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
        faqStartLearning: 'मैं सीखना कैसे शुरू करूं?',
        faqStartLearningAnswer: 'होम पेज से अपनी रुचि का विषय चुनकर शुरू करें। प्रत्येक विषय में चरण-दर-चरण निर्देश और वीडियो ट्यूटोरियल हैं जो आपको सीखने में मदद करेंगे।',
        faqUseMitraYug: 'क्या मैं अपने फोन पर मित्रयुग का उपयोग कर सकता/सकती हूं?',
        faqUseMitraYugAnswer: 'हां! मित्रयुग सभी उपकरणों पर काम करने के लिए डिज़ाइन किया गया है, जिसमें स्मार्टफोन, टैबलेट और कंप्यूटर शामिल हैं। इंटरफ़ेस किसी भी स्क्रीन साइज़ पर आसान उपयोग के लिए अनुकूलित है।',
        faqVoiceAssistance: 'मैं वॉइस असिस्टेंस फीचर का उपयोग कैसे करूं?',
        faqVoiceAssistanceAnswer: 'वॉइस असिस्टेंस को सक्षम करने के लिए टॉप नेविगेशन बार में स्पीकर आइकन पर क्लिक करें। फिर, किसी भी टेक्स्ट पर क्लिक करें ताकि उसे जोर से पढ़ा जा सके।',
        faqMoreHelp: 'यदि मुझे और सहायता की आवश्यकता है तो क्या करूं?',
        faqMoreHelpAnswer: 'आप नीचे दिए गए फॉर्म का उपयोग करके हमारी सहायता टीम से संपर्क कर सकते हैं। हम आपकी मदद के लिए हैं और जल्द से जल्द आपके प्रश्नों का उत्तर देंगे।',
        yourName: 'आपका नाम',
        phoneNumber: 'फोन नंबर',
        yourQuestion: 'आपका प्रश्न',
        sendMessage: 'संदेश भेजें',
    }
};

// Get current language
function getCurrentLanguage() {
    return localStorage.getItem('language') || 'en';
}

// Set current language
function setCurrentLanguage(lang) {
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    updatePageContent();
}

// Update page content based on current language
function updatePageContent() {
    const currentLang = getCurrentLanguage();
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[currentLang][key]) {
            element.textContent = translations[currentLang][key];
        }
    });
}

// Initialize language
document.addEventListener('DOMContentLoaded', () => {
    const currentLang = getCurrentLanguage();
    document.documentElement.lang = currentLang;
    updatePageContent();
}); 